// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPHygXZQ47Yw3IT6UOWWS7Bw5A9Y41I-s',
    appId: '1:485294991410:web:a1a29a24b612d4a923742b',
    messagingSenderId: '485294991410',
    projectId: 'wechatapp',
    authDomain: 'wechatapp-7a602.firebaseapp.com',
    storageBucket: 'wechatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKd0_dfy1YIBPqyJAjjyIGV5QHpBQE3Lo',
    appId: '1:485294991410:android:bf1116f8562d664523742b',
    messagingSenderId: '485294991410',
    projectId: 'wechatapp',
    storageBucket: 'wechatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaeUBobnEF-a8xhRRmBt6fwOtfAObZRzk',
    appId: '1:485294991410:ios:3332be13bdbad0f723742b',
    messagingSenderId: '485294991410',
    projectId: 'wechatapp',
    storageBucket: 'wechatapp.firebasestorage.app',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaeUBobnEF-a8xhRRmBt6fwOtfAObZRzk',
    appId: '1:485294991410:ios:3332be13bdbad0f723742b',
    messagingSenderId: '485294991410',
    projectId: 'wechatapp',
    storageBucket: 'wechatapp.firebasestorage.app',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPHygXZQ47Yw3IT6UOWWS7Bw5A9Y41I-s',
    appId: '1:485294991410:web:ae803fe11cca9ee123742b',
    messagingSenderId: '485294991410',
    projectId: 'wechatapp',
    authDomain: 'wechatapp-7a602.firebaseapp.com',
    storageBucket: 'wechatapp.firebasestorage.app',
  );

}